/**
 * Estilos compartidos por los paneles de gestión académica.
 *
 * Los cuatro paneles son la misma tarjeta con distinto contenido, así que se
 * definen una vez: duplicarlos hacía que cualquier ajuste visual tuviera que
 * repetirse en cuatro archivos y se desincronizara.
 */
export const panel: Record<string, React.CSSProperties> = {
  card: {
    backgroundColor: "#ffffff",
    borderRadius: "20px",
    padding: "24px",
    border: "1px solid #eef2ef",
    boxShadow: "0 4px 16px rgba(0, 0, 0, 0.03)",
    display: "flex",
    flexDirection: "column",
    gap: "16px",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "12px",
  },
  title: {
    fontSize: "17px",
    fontWeight: 700,
    color: "#1e293b",
    margin: "0 0 2px 0",
  },
  subtitle: {
    fontSize: "12px",
    color: "#64748b",
    margin: 0,
  },
  addBtn: {
    padding: "8px 16px",
    backgroundColor: "#f0f7f2",
    color: "#2e7d48",
    border: "1px solid #c8e6d0",
    borderRadius: "10px",
    fontSize: "13px",
    fontWeight: 600,
  },
  form: {
    display: "flex",
    flexDirection: "column",
    gap: "10px",
    padding: "16px",
    backgroundColor: "#f8faf8",
    borderRadius: "12px",
    border: "1px solid #e2e8f0",
  },
  input: {
    width: "100%",
    fontSize: "14px",
  },
  submitBtn: {
    padding: "10px 20px",
    backgroundColor: "#2e7d48",
    color: "#ffffff",
    border: "none",
    borderRadius: "10px",
    fontSize: "14px",
    fontWeight: 700,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  list: {
    display: "flex",
    flexDirection: "column",
    gap: "8px",
  },
  row: {
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    padding: "12px 16px",
    backgroundColor: "#f8faf8",
    border: "1px solid #e2e8f0",
    borderRadius: "12px",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
  },
  rowActive: {
    backgroundColor: "#eaf5ed",
    border: "1px solid #2e7d48",
  },
  rowStatic: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    flexWrap: "wrap",
    gap: "10px",
    padding: "12px 16px",
    backgroundColor: "#f8faf8",
    border: "1px solid #e2e8f0",
    borderRadius: "12px",
  },
  rowTitle: {
    fontSize: "14px",
    fontWeight: 600,
    color: "#1e293b",
  },
  rowMeta: {
    fontSize: "12px",
    color: "#94a3b8",
  },
  muted: {
    fontSize: "13px",
    color: "#94a3b8",
    margin: 0,
  },
  errorBox: {
    backgroundColor: "#fef2f2",
    border: "1px solid #fecaca",
    color: "#991b1b",
    fontSize: "13px",
    padding: "10px 14px",
    borderRadius: "10px",
  },
  warnBox: {
    backgroundColor: "#fef3c7",
    border: "1px solid #fde68a",
    color: "#92400e",
    fontSize: "13px",
    padding: "10px 14px",
    borderRadius: "10px",
  },
  deleteBtn: {
    padding: "6px 12px",
    backgroundColor: "#ffffff",
    color: "#dc2626",
    border: "1px solid #fecaca",
    borderRadius: "8px",
    fontSize: "12px",
    fontWeight: 600,
    cursor: "pointer",
  },
  link: {
    fontSize: "12px",
    color: "#2e7d48",
    fontWeight: 600,
    wordBreak: "break-all",
  },
  rolePill: {
    fontSize: "11px",
    fontWeight: 700,
    color: "#2e7d48",
    backgroundColor: "#eaf5ed",
    padding: "4px 12px",
    borderRadius: "10px",
    textTransform: "capitalize",
  },
}
